[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    'pallets/organizations',
    'pallets/identifiers',
    'pallets/supply-assets',
    'pallets/validator-set',
    'runtime',
]
